import { useState, useEffect } from "react";
import { useNavigate } from "react-router";
import { 
  HeartPulse, 
  LayoutDashboard, 
  Activity, 
  Pill, 
  Heart, 
  TrendingUp, 
  ChevronLeft, 
  ChevronRight,
  ShieldCheck,
  Zap,
  Clock,
  ArrowRight
} from "lucide-react";

const slides = [
  {
    title: "Your Intelligent Recovery Companion",
    description: "RecoverWell helps you bridge the gap between hospital discharge and full recovery with AI-powered monitoring and guidance.",
    icon: <HeartPulse className="w-16 h-16 text-primary" />,
    image: "/api/placeholder/800/600",
    color: "bg-primary/5"
  },
  {
    title: "Smart Recovery Dashboard",
    description: "Get a bird's-eye view of your recovery journey. Monitor vitals, progress percentages, and upcoming tasks in one beautiful interface.",
    icon: <LayoutDashboard className="w-16 h-16 text-emerald-500" />,
    image: "/api/placeholder/800/600",
    color: "bg-emerald-50"
  },
  {
    title: "Precise Health Logging",
    description: "Track your symptoms, mood, and pain levels daily. Our system analyzes trends to identify potential risks before they become issues.",
    icon: <Activity className="w-16 h-16 text-blue-500" />,
    image: "/api/placeholder/800/600",
    color: "bg-blue-50"
  },
  {
    title: "Medication Reminders",
    description: "Never miss a dose. Automatically extract medication schedules from your discharge summary and track when you've taken each dose.",
    icon: <Pill className="w-16 h-16 text-purple-500" />,
    image: "/api/placeholder/800/600",
    color: "bg-purple-50"
  },
  {
    title: "AI-Powered Recovery Guide",
    description: "Receive personalized diet, exercise, and care advice generated by Gemini AI specifically for your surgery and diagnosis.",
    icon: <Heart className="w-16 h-16 text-rose-500" />,
    image: "/api/placeholder/800/600",
    color: "bg-rose-50"
  }
];

export function HomePage() {
  const navigate = useNavigate();
  const [currentSlide, setCurrentSlide] = useState(0);

  useEffect(() => {
    const timer = setInterval(() => {
      setCurrentSlide((prev) => (prev + 1) % slides.length);
    }, 6000);
    return () => clearInterval(timer);
  }, []);

  const nextSlide = () => setCurrentSlide((prev) => (prev + 1) % slides.length);
  const prevSlide = () => setCurrentSlide((prev) => (prev - 1 + slides.length) % slides.length);

  return (
    <div className="min-h-screen bg-background flex flex-col overflow-x-hidden">
      {/* Navigation */}
      <header className="fixed top-0 left-0 right-0 z-50 bg-background/80 backdrop-blur-md border-b border-border">
        <div className="max-w-7xl mx-auto px-4 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-9 h-9 rounded-lg bg-primary flex items-center justify-center">
              <HeartPulse className="w-5 h-5 text-white" />
            </div>
            <span className="text-[18px] font-bold tracking-tight text-foreground">RecoverWell</span>
          </div>
          <button 
            onClick={() => navigate("/sign-in")}
            className="px-5 py-2 bg-primary text-white text-[14px] font-medium rounded-full hover:bg-primary/90 transition-all shadow-sm"
          >
            Get Started
          </button>
        </div>
      </header>

      {/* Hero / Slider Section */}
      <section className="pt-32 pb-20 px-4 flex-1 flex flex-col items-center">
        <div className="max-w-6xl w-full relative">
          <div className="relative w-full overflow-hidden">
            <div 
              className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center rounded-3xl p-8 lg:p-12 border border-border/50 transition-all duration-500 ease-in-out"
              style={{ backgroundColor: slides[currentSlide].color.includes("/") ? "var(--primary-light)" : "transparent" }}
            >
              <div className="space-y-6">
                <div className="p-4 bg-white rounded-2xl w-fit shadow-sm">
                  {slides[currentSlide].icon}
                </div>
                <h2 className="text-4xl lg:text-5xl font-extrabold text-foreground leading-[1.1]">
                  {slides[currentSlide].title}
                </h2>
                <p className="text-lg text-muted-foreground leading-relaxed max-w-xl">
                  {slides[currentSlide].description}
                </p>
                <div className="flex items-center gap-4 pt-4">
                  <button 
                    onClick={() => navigate("/sign-in")}
                    className="group px-8 py-3.5 bg-primary text-white rounded-full font-semibold flex items-center gap-2 hover:bg-primary/90 transition-all shadow-md active:scale-95"
                  >
                    Start Your Recovery
                    <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
                  </button>
                </div>
              </div>

              <div className="relative aspect-[4/3] rounded-2xl overflow-hidden shadow-2xl border border-border bg-card">
                <div className="absolute inset-0 bg-gradient-to-br from-primary/10 to-transparent" />
                <div className="absolute inset-0 flex items-center justify-center">
                   <div className="text-center p-8">
                     <div className="w-20 h-20 bg-muted rounded-full mx-auto mb-4 flex items-center justify-center">
                        {slides[currentSlide].icon}
                     </div>
                     <p className="text-[13px] text-muted-foreground italic font-medium">Dashboard Interface Preview</p>
                   </div>
                </div>
              </div>
            </div>
          </div>

          {/* Controls */}
          <div className="flex items-center gap-4 mt-8 justify-center">
            <button 
              onClick={prevSlide}
              className="p-3 rounded-full border border-border bg-card hover:bg-muted transition-colors shadow-sm"
            >
              <ChevronLeft className="w-5 h-5" />
            </button>
            <div className="flex gap-2">
              {slides.map((_, i) => (
                <button 
                  key={i}
                  onClick={() => setCurrentSlide(i)}
                  className={`w-3 h-3 rounded-full transition-all ${currentSlide === i ? "bg-primary w-8" : "bg-muted"}`}
                />
              ))}
            </div>
            <button 
              onClick={nextSlide}
              className="p-3 rounded-full border border-border bg-card hover:bg-muted transition-colors shadow-sm"
            >
              <ChevronRight className="w-5 h-5" />
            </button>
          </div>
        </div>
      </section>

      {/* Trust Section */}
      <section className="py-20 bg-muted/30 border-y border-border">
        <div className="max-w-7xl mx-auto px-4 grid grid-cols-1 md:grid-cols-3 gap-12 text-center">
          <div className="space-y-4">
            <div className="w-12 h-12 bg-emerald-100 rounded-full flex items-center justify-center mx-auto">
              <ShieldCheck className="w-6 h-6 text-emerald-600" />
            </div>
            <h3 className="text-lg font-bold">Secure Data</h3>
            <p className="text-[14px] text-muted-foreground">Your health information is encrypted and visible only to you and your authorized care team.</p>
          </div>
          <div className="space-y-4">
            <div className="w-12 h-12 bg-blue-100 rounded-full flex items-center justify-center mx-auto">
              <Zap className="w-6 h-6 text-blue-600" />
            </div>
            <h3 className="text-lg font-bold">AI Assistance</h3>
            <p className="text-[14px] text-muted-foreground">Using Google Gemini API to extract complex clinical data from your documents effortlessly.</p>
          </div>
          <div className="space-y-4">
            <div className="w-12 h-12 bg-purple-100 rounded-full flex items-center justify-center mx-auto">
              <Clock className="w-6 h-6 text-purple-600" />
            </div>
            <h3 className="text-lg font-bold">24/7 Monitoring</h3>
            <p className="text-[14px] text-muted-foreground">Stay connected with your recovery plan even late at night with automated reminders.</p>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="py-12 bg-background border-t border-border">
        <div className="max-w-7xl mx-auto px-4 flex flex-col md:flex-row justify-between items-center gap-6">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-primary flex items-center justify-center">
              <HeartPulse className="w-4 h-4 text-white" />
            </div>
            <span className="text-[16px] font-bold">RecoverWell</span>
          </div>
          <p className="text-[14px] text-muted-foreground">© 2026 RecoverWell Healthcare Solutions. All rights reserved.</p>
          <div className="flex items-center gap-6 text-[14px] text-muted-foreground">
            <a href="#" className="hover:text-primary transition-colors">Privacy Policy</a>
            <a href="#" className="hover:text-primary transition-colors">Terms of Service</a>
          </div>
        </div>
      </footer>
    </div>
  );
}
